title: Korepetycje Online
description: Strona do zapis√≥w na korepetycje z matematyki, chemii i fizyki
theme: minimal-mistakes-jekyll
url: "https://szmigielms.github.io"
baseurl: "/korepetycje-online"
